title: Seldovia Scrapbook Pages
description: This is a work in progress to compile interesting information about Seldovia's history
theme: jekyll-theme-leap-day

collections:
  people:
    output: true
