title: Seldovia remembers
description: This is a work in progress to compile interesting information about Seldovia's history

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled:     true
  collections: true
  
collections:
  people:
    output: true
    permalink: /:collection/:name
  families:
    output: true
    permalink: /:collection/:name
  boats:
    output: true
    permalink: /:collection/:name
  enterprises:
    output: true
    permalink: /:collection/:name
  resources:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: "_people"
      type: people
    values:
      layout: person
  - scope:
      path: "_families"
      type: families
    values:
      layout: default
  - scope:
      path: "_boats"
      type: boats
    values:
      layout: default
  - scope:
      path: "_enterprises"
      type: enterprises
    values:
      layout: default
  - scope:
      path: "_resources"
      type: resources
    values:
      layout: default
