title: Seldovia Scrapbook Pages
description: This is a work in progress to compile interesting information about Seldovia's history
theme: jekyll-theme-leap-day

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled:     true
  collections: true
  
collections:
  people:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: "_people"
      type: people
    values:
      layout: person
